-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 22, 2022 at 08:34 AM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 7.3.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `story`
--
CREATE DATABASE IF NOT EXISTS `story` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `story`;

-- --------------------------------------------------------

--
-- Table structure for table `story`
--

DROP TABLE IF EXISTS `story`;
CREATE TABLE IF NOT EXISTS `story` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `title` text NOT NULL,
  `body` longtext NOT NULL,
  `p_date` date NOT NULL,
  `user_id` varchar(50) DEFAULT NULL,
  `str_date` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `story`
--

INSERT INTO `story` (`id`, `title`, `body`, `p_date`, `user_id`, `str_date`) VALUES
(1, 'New story', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. sfgfsg fsgfs', '2022-05-25', 'GGxpWZ008', ' 25 May 2022'),
(6, 'Great editing', 'Yes this is great editing.', '2022-05-18', 'TZxpWZ007', ' 18 May 2022'),
(10, 'Final check for story', 'Yes this is my final checkup', '2022-05-18', 'TZxpWZ007', '18 May 2022'),
(11, 'This band-aid like tracker could shed light on your insomnia', 'We spend around a third of our lives asleep. At least, we\'re supposed to. In reality, many of us aren\'t getting enough sleep — in a global study conducted in 2020, over a third of adults reported sleeping problems, exacerbated by the Covid-19 pandemic.\r\n\r\nThere are around 80 different kinds of sleep disorders, including insomnia, sleep apnea and restless leg syndrome, according to the Cleveland Clinic.\r\nBut for doctors to diagnose most of them, patients usually need to go to a clinic and undergo a sleep study. Typically, a technician tapes or glues dozens of sensors to the patient\'s head and body. The sensors are connected by wires to a computer, which sends data to the technician, who monitors the patient from a nearby room.\r\nIsraeli startup X-trodes is hoping to change that. Founded in 2020, the company has developed a sleep tracker fitted with tiny sensors that sticks to the skin like a band-aid and can be used at home.', '2022-01-04', 'GGxpWZ008', '04 January 2022'),
(13, 'Bangladesh vs Sri Lanka, 1st Test, Day 4 Live Score: Mushfiqur Rahim Nears Ton As Bangladesh Close In On Sri Lanka\'s Total', 'BAN vs SL, 1st Test, Day 4 Live Updates: Mushfiqur Rahim has put Bangladesh in a commanding position against Sri Lanka on Day 4 of the ongoing first Test at the Zahur Ahmed Chowdhury Stadium in Chattogram. The hosts are five wickets down but are closing in on the visitors total of 397. Mushfiqur and Litton Das had steadied Bangladesh\'s ship after Tamim Iqbal had to retire hurt on a score of 133 on Day 3. The pair added 201 runs for the fourth wickets before Das and Tamim were dismissed in quick succession after the lunch. Earlier, Angelo Mathews\' marathon knock of 199 had propelled Sri Lanka to a total of 397. (LIVE SCORECARD)', '2022-05-19', 'GGxpWZ008', '19 May 2022'),
(14, 'Bangladesh vs Sri Lanka, 1st Test, Day 4 Live Score: Mushfiqur Rahim Nears Ton As Bangladesh Close In On Sri Lanka\'s Total', 'BAN vs SL, 1st Test, Day 4 Live Updates: Mushfiqur Rahim has put Bangladesh in a commanding position against Sri Lanka on Day 4 of the ongoing first Test at the Zahur Ahmed Chowdhury Stadium in Chattogram. The hosts are five wickets down but are closing in on the visitors total of 397. Mushfiqur and Litton Das had steadied Bangladesh\'s ship after Tamim Iqbal had to retire hurt on a score of 133 on Day 3. The pair added 201 runs for the fourth wickets before Das and Tamim were dismissed in quick succession after the lunch. Earlier, Angelo Mathews\' marathon knock of 199 had propelled Sri Lanka to a total of 397. (LIVE SCORECARD)', '2022-05-19', 'GGxpWZ008', '19 May 2022'),
(15, 'The Bangladesh story', 'Bangladesh is celebrating its 50th anniversary. Once called a \"basket case\" by Henry Kissinger, it is now considered as a role model. Bangladesh\'s national income has multiplied 50 times, per capita income 25 times (higher than India\'s and Pakistan\'s), and food production four times. Population growth was contained at 2.5 times, raising per capita food availability. Exports have grown 100 times and poverty is down to 20 percent from 60 percent in 1990. Life expectancy has risen to 72. Most social indicators are better compared to regional countries, except Sri Lanka. The value of the Human Development Index increased 60 percent.\r\n\r\nMost of this progress has been achieved in the last three decades as the first two experienced anaemic growth and political turmoil. To put their progress in perspective, Pakistan\'s per capita income in 1990 was twice as much as Bangladesh\'s but has fallen today to only seven-tenth. Between 2011 and 2019, before Covid struck, Bangladesh\'s average GDP growth ranged between 7 percent and 8 percent—almost twice as fast as Pakistan\'s.', '2022-05-20', 'HZ007xGG200', '20 May 2022'),
(19, '‘Shrek,’ ‘Puss in Boots’ Getting Rebooted (EXCLUSIVE)', '“Shrek” and “Puss in Boots” are getting rebooted and Chris Meledandri, the man behind “Despicable Me,” is overseeing their revival.\r\n\r\nUniversal Pictures has tasked Meledandri with finding some fresh story lines to reintroduce the lovable ogre and the sword-wielding feline to new generations of moviegoers. One thing the animation guru doesn’t want to mess with is with the vocal performances. Part of the popularity of “Shrek” is attributable to a voice cast that included Mike Myers, Eddie Murphy and Antonio Banderas, and in a lengthy profile in Variety, Meledandri says he would like to get the band back together.\r\n\r\n“When you look back on those vocal performances they’re awesome, and while you certainly could make a case for a complete reinvention, I find myself responding to my own nostalgic feelings of wanting to go back to those characterizations,” explains Meledandri. “The challenge for us has been to find something that really does feel like it’s not simply yet another film in a series of sequels.”\r\n\r\nThe move comes after the studio’s parent company, Comcast, bought DreamWorks Animation, the studio behind “Shrek,” in 2016 for $3.8 billion. Initially, there had been speculation that Meledandri, whose Illumination Entertainment is co-owned by Universal, would be asked to oversee DreamWorks Entertainment. However, Meledandri says he came to feel that he couldn’t manage the two companies and still maintain the same level of quality in the films he makes.\r\n\r\n“The way in which I work with my team to make movies is very intensive and hands-on, and it really doesn’t allow me the opportunity to think about running a second operation,” says Meledandri. “I love the process of making films and working with artists. I don’t think I’m particularly great at managing companies.”\r\n\r\nEven though he hasn’t cracked the code on “Shrek,” Meledandri sounds confident that it’s only a matter of time before moviegoers get to revisit the magical fairy tale setting that made the original movies such a treat.\r\n\r\n“There’s a tremendous amount of fun to be had in that world, but it’s a high bar to find a story that’s truly world,” said Meledandri. “You want to find something in the narrative that really feels like a departure.”\r\n\r\nIllumination’s next film, “The Grinch,” opens in theaters on Friday.', '2022-05-20', 'TZxpWZ007', '20 May 2022'),
(21, 'RCB sneak into playoffs after Tim David, Jasprit Bumrah knock Delhi Capitals out', 'Ten balls. That\'s all it took. Ten balls of carnage to end Delhi Capitals\' season and thrust Royal Challengers Bangalore into the playoffs.\r\n\r\nTim David would have been out for 0 had they opted to review a caught-behind decision in the 15th over when the equation was 65 off 33.\r\n\r\nInstead he got to face 10 more balls and score 34 heartbreaking runs to punish Rishabh Pant and his men for an error that will haunt them for what will feel like forever.\r\n\r\nBumrah roars\r\n\r\nEven in this atrocious season, Mumbai Indians managed to have a say in who would win the IPL. They restricted Capitals to 159 for 7 in a must-win game.\r\n\r\nJasprit Bumrah (4-0-25-3) was extraordinary. Even on a slow pitch, he hurried batters with his pace and picked up the kind of wickets that will form a fast-bowling hype reel. Prithvi Shaw bounced out. Mitchell Marsh caught at first slip. Rovman Powell cuh-lean bowled.\r\n\r\nThe thought of him bowling in tandem with Jofra Archer next season is just bonkers.', '2022-05-22', 'GGxpWZ008', '22 May 2022'),
(22, 'Hollywood forgives Will Smith? Finally some good news for the actor', 'Sony decides to back Will Smith\r\n\r\nSony chairman Tom Rothman has spoken openly about his company\'s intentions to give its OK to a new film in the Bad Boys franchise, in which Smith stars, after the executive was questioned about whether the actor\'s participation in the movie was on hold.\r\n\r\n\"No. That was inaccurate, that movie\'s been in development and still is. There weren\'t any brakes to pump because the car wasn\'t moving,\" Rothman told Deadline.\"That was a very unfortunate thing that happened, and I don\'t think it\'s really my place to comment, except to say that I\'ve known Will Smith for many years, and I know him to be a good person. That was an example of a very good person having a very bad moment, in front of the world. I believe his apology and regret is genuine, and I believe in forgiveness and redemption,\" Sony chairman added.\r\n\r\nThis information comes after several of Smith\'s projects were put on hold, such as the Netflix action film \"Fast and Loose\" and \"Bright 2,\" plus AppleTV+ film \"Emancipation\" also pushed its release date back.', '2022-05-22', 'GGxpWZ008', '22 May 2022'),
(23, 'New WB CEO Reportedly Meeting With JK Rowling About More Harry Potter', 'Warner Bros.’ new CEO David Zaslav reportedly has plans to meet with Harry Potter creator JK Rowling to discuss the beloved franchise. Much has changed since the final installment of the eight-film series was released, with the IP’s spinoff franchise, Fantastic Beasts and Where to Find Them, simply not reaching the same heights as the Potter films did. Add to this the isolating stances Rowling has taken in recent years, and its clear something needs to change.\r\n\r\nOf course, Harry Potter fans are a patient group, having learned quite early on that Rowling did not plan to write any more books in the bestselling series. As a result, fans transferred their collective enthusiasm to the arrival of Fantastic Beasts, as well as other spinoff projects such as the Potter stage production (which wasn’t written by Rowling) and the upcoming open world video game Hogwarts Legacy. Yet as exciting as these things are, all of them leave out further adventures for Harry, Ron and Hermione. The more recent news that HBO Max is possibly developing a Harry Potter TV show offers some promise for discovering more of the franchise’s apparent limitlessness, but still the idea of more Potter films continues to haunt fans.', '2022-05-04', 'Jkhp435000', '04 May 2022'),
(24, 'J.K. Rowling Approached To Take Harry Potter Universe Ahead By Warner Bros CEO David Zaslav?', 'The world is awaiting the comeback of the wizarding world that includes the iconic character Harry Potter (yes, we do acknowledge Fantastic Beasts’ presence but let’s be honest which one has more weightage). There have been speculations and rumours that have spoken about the return of the universe and that there have been several projects that have been allegedly given green signal by the studio. But the cast members including Daniel Radcliffe and Rupert Grint have spoken otherwise.\r\n\r\nFor the unversed, ever since the main franchise ended with the planned 8 film series, Harry Potter fans have been patient enough for another pathbreaking phase of the world. The Fantastic Beasts And Where To Find Them did create the buzz but failed to create a legacy like its predecessor. Now that Warner Bros has a new CEO looks like he has reignited hopes for the fans.', '2022-05-22', 'Jkhp435000', '22 May 2022'),
(25, 'EA bans over 150 FIFA players from FGS and other esports competition', 'FIFA Esports witnesses a huge ban wave in the past few days. As the competitive arena of the game grew, EA Games (the producer of the game) began to take tougher and faster decisions against the irregularities and rule violations made. EA announced that more than 150 players have been banned from competition for different periods of time, along with a statement shared on its website.\r\n\r\n\r\nPlayers signed to the EA SPORTS FIFA 22 Global Series Rulebook, to compete in the EA Sports FIFA 22 Global Series. The company said that verified players should have a higher standard than other players. It also underlined that otherwise they would face higher-than-normal penalties.\r\n\r\nLet’s look at some players who violated the rules and why they were penalized.', '2022-05-20', 'NoobFaiaz420', '20 May 2022'),
(26, 'Potential candidates for the new Dignitas CSGO roster', 'Dignitas are hurting, and much of it stems from their inability to qualify for PGL Major Antwerp 2022. The winds of change are blowing as the organization announced a roster-revamp.\r\n\r\nBut the big question remains: Is this a knee-jerk reaction or a well thought out strategy aimed at a rebuild\r\n\r\nOne may argue that it’s entirely possible the players on the transfer list may come back in a rejigged roster, but for the moment, they have all been told to pursue other options if available. It can’t even be a cryptic way of putting the message out when the team says they want to build a competitive roster by letting go people. It’s as direct a message as it can get. Point blank.', '2022-05-19', 'NoobFaiaz420', '19 May 2022'),
(27, 'Overwatch League 2022 season becomes top heavy – Week 3 Preview', 'The Overwatch League just concluded its second week, coming fresh off more changes to the OW 2 beta.\r\n\r\nThe first two weeks have been tumultuous so far. We’ve had heroes removed the game, big changes implemented, and even a team forced to replay matches. There’s been plenty of shocking results. The rankings for teams is currently looking different to what players may have expected.\r\n\r\nThis is what you might have missed at the OWL 2022 Week 2, and what to look for heading into Week 3.The OPWL 2022 Week 2 matches kicked off with Florida Mayhem sweeping Vancouver 3-0. Washington also managed that result against Atlanta on the first day of matches. San Francisco Shock finished up winning their match against Houston 3-1 Most of these are in-line with the OWL power rankings and what we can expect from the teams.\r\n\r\nIn terms of the standings though this puts Shock fully on top with 4 matches played and 4 won. They went into the season with a pretty new squad from contenders.  Their success so far could be the start of a great run for Shock. On the other end of the spectrum, Vancouver has now lost four games. This puts them pretty firmly at the bottom of the rankings.', '2022-05-19', 'NoobFaiaz420', '19 May 2022'),
(28, 'Taylor Swift receives an honorary degree and addresses NYU graduating class', 'Welcome to New York (University), it\'s been waiting for you (Taylor Swift).\r\n\r\nThe 11-time Grammy winner delivered a commencement speech to NYU grads and received an honorary degree at Yankee Stadium on Wednesday. Swift blew kisses and waved as she made her way to the stage among other honorary doctorates, which prompted roaring applause from the stadium.\r\n\r\n\"Hi, I\'m Taylor,\" she said when addressing the crowd after receiving her honorary degree. \"Last time I was in a stadium this size I was dancing in heels and wearing a glittery leotard. This outfit is much more comfortable.\"\r\n\r\nShe went on to joke about why she was likely selected by NYU to receive the honor this year. \"I\'m 90 percent sure the reason I\'m here is because I have a song called \'22,\'\" she said, adding that she was elated to celebrate the graduating class.\r\n\r\nWhen the pop star was announced as both a degree recipient and speaker in March, Swifties went into a frenzy. Many haggled NYU students for tickets to the event, NBC New York reported, and offered them money to get a ticket to graduation.\r\n\r\nEach student gets two commencement tickets, according to the university, which also has a policy in place that bans students from selling or auctioning off their commencement tickets.', '2022-05-21', 'HZ007xGG200', '21 May 2022'),
(29, 'Kendrick Lamar is back. Here\'s what to know about the new album \'Mr. Morale and the Big Steppers.', 'Kendrick Lamar is finally back.\r\n\r\nThe rapper on Friday dropped his latest album, \"Mr. Morale and the Big Steppers.\" It\'s his first studio album in five years since 2017\'s \"Damn.\"\r\n\r\nLamar is known as a virtuoso who constantly pushes musical and artistic boundaries with his projects. He\'s earned 14 Grammy awards for his work, and “Damn” was the first non-classical and non-jazz album to win the Pulitzer Prize for music in 2018.\r\n\r\nHere\'s everything you should know about his new music.', '2022-05-08', 'HZ007xGG200', '08 May 2022'),
(30, 'Young Thug\'s racketeering charges show how hip-hop is still criminalized', 'Influential rappers Young Thug and Gunna were arrested last week under an 88-page indictment that named nearly 30 people and contained evidence going as far back as 2013. These high-profile arrests mark a rising trend in the criminalization of hip-hop artists under the RICO Act — that\'s short for Racketeer Influenced and Corrupt Organization, a law that was originally designed to fight organized crime like the mafia.Louder Than A Riot hosts Sidney Madden and Rodney Carmichael sit down with Weekend Edition Sunday\'s Ayesha Rascoe to unpack this news and examine how the artists are being policed — from the application of the word \"gang\" to describe rap crews, to the use of art as evidence.\r\n\r\nIn this update to our previous reporting on the cases of DJ Drama, Mac Phipps and Bobby Shmurda, we consider the tension between fans that applaud street cred and the law enforcement that uses it as evidence.\r\n\r\nTo connect with us, follow the show on Twitter @LouderThanARiot, or send us an email at louder@npr.org.', '2022-05-02', 'HZ007xGG200', '02 May 2022'),
(31, 'U2\'s Bono and the Edge held a concert in a Kyiv subway station in support of Ukraine', 'Two members of the Irish rock band U2 played a concert in a Kyiv subway station on Sunday, performing some of their classics and sharing the stage with Ukranian musicians.\r\n\r\nBono and the Edge wrote on Twitter that Ukranian President Volodymyr Zelenskyy had invited them to perform in Kyiv \"as a show of solidarity with the Ukrainian people.\"And that\'s what they did, playing a roughly 40-minute acoustic set to a crowd of about 100 people gathered in the relative safety of the Khreshchatyk metro station-turned-bomb shelter.\r\n\r\nThey performed hits like \"With or Without You,\" \"Desire,\" \"Angel of Harlem\" and \"Vertigo\" to a rapt audience that included soldiers in military fatigues.\r\n\r\nBono addressed the audience between songs, praising the Ukranian resistance and expressing his hopes for peace. At one point, the Irish Times notes, he invoked the struggles of his own home country.', '2022-05-12', 'HZ007xGG200', '12 May 2022'),
(32, '2022 Pulitzer Prizes in arts and letters go to \'Fat Ham\' and \'The Netenyahus\'', 'They\'re the most prestigious awards in America, not just for journalists, but historians, poets, playwrights, non-fiction writers, composers and novelists.\r\n\r\nNovelist Joshua Cohen won his first fiction Pulitzer for The Netanyahus: An Account of a Minor and Ultimately Even Negligible Episode in the History of a Very Famous Family. A winner of the 2021 National Jewish Book Award, it was described by the Pulitzer committee as \"a mordant, linguistically deft historical novel about the ambiguities of the Jewish-American experience, presenting ideas and disputes as volatile as its tightly-wound plot.\"\r\n\r\nIn the category of drama, James Ijames won for Fat Ham, a comedy earning rave reviews during its staging at the Wilma Theater in the playwright\'s hometown of Philadelphia. Fat Ham opens very soon at New York\'s Public Theater. It\'s based on a play you may have heard of — Hamlet by William Shakespeare — but set at a southern barbecue restaurant. In a review last year, The New York Times described Fat Ham as \"hilarious yet profound,\" adding \"it is the rare takeoff that actually takes off — and then flies in its own smart direction.\"', '2022-05-26', 'HZ007xGG200', '26 May 2022'),
(33, '\"DCeased: War of the Undead Gods,\" The Final Chapter in the Best-Selling Trilogy Arrives August 9', 'DC\r\nMay 18, 2022\r\n\"DCeased: War of the Undead Gods,\" The Final Chapter in the Best-Selling Trilogy Arrives August 9\r\nMain Cover, \"DCeased: War of the Undead Gods\" #1 by Trevor Hairsine\r\n \r\n\r\nFrom the original DCeased, to DCeased: Dead Planet, DCeased: Unkillables, to DCeased: Hope at World’s End, acclaimed writer Tom Taylor and artist Trevor Hairsine turned the DCU upside down, combining horror, heroism, and hope in the face of Armageddon.\r\n\r\n \r\n\r\nTaylor and Hairsine reunite for the last chapter in this fan-favorite franchise, DCeased: War of the Undead Gods. This eight-issue monthly limited series arrives in comic book stores and participating digital platforms on Tuesday, August 9.\r\n\r\n \r\n\r\nWhat began as a battle for Earth has become a war for the galaxy! The emergence of a reborn, undead Darkseid in DCeased: Dead Planet sets the stage for the most devastating conflict yet for Batman, Superman, and Wonder Woman! As the Anti-Life Equation spreads into the cosmos, the survivors of Earth prepare for the coming apocalypse and realize their only hope could lie in the most powerful surviving hero from the first DCeased series.', '2022-05-01', 'NoobFaiaz420', '01 May 2022'),
(34, '\"The Batman\" Sequel Announced', 'Burbank, CA) – Warner Bros. Pictures announced today that director Matt Reeves has begun scripting a sequel to “The Batman,” which he and Dylan Clark would also return to produce.  The news comes on the heels of the current film passing the $750 million mark at the global box office.  The announcement was made today by Toby Emmerich, Chairman, Warner Bros. Pictures Group, and Reeves himself, who joined Emmerich onstage during his opening remarks at the Warner Bros. Pictures presentation at CinemaCon in Las Vegas.\r\n\r\n \r\n\r\nHBO Max recently announced a series centered around Colin Farrell as The Penguin, derived directly from the universe launched by the “The Batman.”  Reeves is currently reteaming with J.J. Abrams and DC universe veteran Bruce Timm on the streamer’s upcoming animated series “Batman: Caped Crusader.”  The filmmaker’s prior films include the hugely successful “Planet of the Apes” franchise, the acclaimed fantasy horror film “Let Me In,” and the sci-fi horror hit “Cloverfield,” among others.  Reeves’ additional credits include the popular TV series “Felicity,” which he co-created with Abrams, as well as the series “Ordinary Joe,” “Lift,” “Mother/Android,” “Away,” “Tales from the Loop” and “The Passage,” among others.\r\n\r\n \r\n\r\nThe filmmaker is represented by CAA, 3Arts Entertainment and Jackoway Austen.', '2022-05-03', 'NoobFaiaz420', '03 May 2022'),
(35, '\"Teen Titans Go!\" Renewed For Season Eight Plus \"Mayhem in the Multiverse\" Premieres This Spring', 'Burbank, CA)—WarnerMedia Kids & Family announced today exciting news surrounding the hit Teen Titans Go! franchise. To kickstart a super-powered summer, the Teen Titans and DC Super Hero Girls will reunite during Memorial Day weekend to combat Lex Luthor and his unified gang of DC Super-Villains in Teen Titans Go! & DC Super Hero Girls: Mayhem in the Multiverse. The all-new, feature-length animated TV movie event from Warner Bros. Animation promises action, adventure, plenty of hilarious moments and will be available from Warner Bros. Home Entertainment on Blu-ray Combo Pack (USA $24.98 SRP; Canada $29.98 SRP), DVD (USA $19.98 SRP; Canada $24.98 SRP) and Digital starting May 24, 2022. Fans can also catch the movie event on Cartoon Network premiering Saturday, May 28 and then on HBO Max beginning June 28.\r\n \r\n\r\nAlso announced today, Cartoon Network has picked up another season of Teen Titans Go! from Warner Bros. Animation. Season eight will premiere later this year and will continue expanding the Teen Titans universe, debuting new characters from the DC Universe including Beard Hunter, King Shark and many more as well as welcoming new surprise celebrity guests. As the longest running animated series in DC history, season eight will also mark the series reaching the 400th episode milestone.\r\n\r\n \r\n\r\n\"The undeniable success of Teen Titans Go!, with its signature blend of action and subversive Super Hero humor, is a testament to the phenomenal work of executive producer Pete Michail and the show team,” said Sam Register,  President, Warner Bros. Animation and Cartoon Network Studios. “Seven seasons, one theatrical feature film, multiple specials, celebrity cameos, and no end in sight, this show has carved out its own lane in the acclaimed legacy established by the original Teen Titans animated series.\"', '2022-04-22', 'NoobFaiaz420', '22 April 2022'),


-- --------------------------------------------------------

--
-- Table structure for table `user_data`
--

DROP TABLE IF EXISTS `user_data`;
CREATE TABLE IF NOT EXISTS `user_data` (
  `user_id` varchar(50) NOT NULL,
  `password` varchar(20) NOT NULL,
  `full_name` varchar(70) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user_data`
--

INSERT INTO `user_data` (`user_id`, `password`, `full_name`) VALUES
('GGxpWZ008', 'Whileloop007', 'Md Habibur Rahman'),
('HZ007xGG200', 'Whileloop007', 'Md. Hasan Imam'),
('Jkhp435000', 'Laravel008', 'J.K. Rowling'),
('NoobFaiaz420', 'Noob420', 'Faiaz Khan'),
('TZxpWZ007', 'Whileloop007', 'Md. Abdur Rahman');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `story`
--
ALTER TABLE `story`
  ADD CONSTRAINT `story_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user_data` (`user_id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
